fix build on latest mac - use reference instead of copy
Summary:
On the latest version of clang, it is now an error to use a copy in a for loop, instead we should mark this as a reference.

Output from clang:
```
stderr: fbandroid/native/redex-stable/libredex/DexAnnotation.cpp:810:19: error: loop variable 'pair' of type 'const DexAnnotationElement' creates a copy from type 'const DexAnnotationElement' [-Werror,-Wrange-loop-analysis]
  for (auto const pair : *annos) {
                  ^
```

From https://stackoverflow.com/a/29860056

> • Use auto && for the ability to modify and discard values of the sequence within the loop. (That is, unless the container provides a read-only view, such as std::initializer_list, in which case it will be effectively an auto const &.)
•  Use auto & to modify the values of the sequence in a meaningful way.
•  Use auto const & for read-only access.
•  Use auto to work with (modifiable) copies.

Reviewed By: NTillmann, agampe

Differential Revision: D27064108

fbshipit-source-id: 54303a2994e38bcf1f52e7fe33fbae2377e8686c