Avoid creating a deobfuscated name alias when a type already exists
Summary:
After refactoring in D13582888 an alias to a type is now created using deobfuscated names, however, given that Proguard generates mappings such as:

```
android.support.v7.widget.SearchView$1 -> android.support.v7.widget.SearchView$1:
android.support.v7.widget.SearchView$10 -> android.support.v7.widget.SearchView$2:
android.support.v7.widget.SearchView$2 -> android.support.v7.widget.SearchView$3:
android.support.v7.widget.SearchView$3 -> android.support.v7.widget.SearchView$4:
android.support.v7.widget.SearchView$4 -> android.support.v7.widget.SearchView$5:
android.support.v7.widget.SearchView$5 -> android.support.v7.widget.SearchView$6:
android.support.v7.widget.SearchView$6 -> android.support.v7.widget.SearchView$7:
android.support.v7.widget.SearchView$7 -> android.support.v7.widget.SearchView$8:
android.support.v7.widget.SearchView$8 -> android.support.v7.widget.SearchView$9:
android.support.v7.widget.SearchView$9 -> android.support.v7.widget.SearchView$10:
```
where unfortunately obfuscated name does match another type causing Redex to crash:
```
3   libsystem_c.dylib                   0x00007fff6d69f1c9 abort + 127
18  libsystem_pthread.dylib             0x00007fff6d7ea305 _pthread_body + 126
8   libc++abi.dylib                     0x00007fff6ad33be2 __cxa_get_exception_ptr + 0
11  redex-all                           0x0000000105cacdfe _ZN12RedexContext15alias_type_nameEP7DexTypeP9DexString + 126
11  redex-all                           0x0000000105cacdfe _ZN12RedexContext15alias_type_nameEP7DexTypeP9DexString + 126
11  redex-all                           0x0000000105cacdfe _ZN12RedexContext15alias_type_nameEP7DexTypeP9DexString + 126
19  libsystem_pthread.dylib             0x00007fff6d7ed26f _pthread_start + 70
12  redex-all                           0x0000000105b498d2 _ZN8DexClass21set_deobfuscated_nameERKNSt3__112basic_stringIcNS0_11char_traitsIcEENS0_9allocatorIcEEEE + 338
7   libc++abi.dylib                     0x00007fff6ad33dfe _ZSt11__terminatePFvvE + 8
8   libc++abi.dylib                     0x00007fff6ad33be2 __cxa_get_exception_ptr + 0
9   libc++abi.dylib                     0x00007fff6ad26bb9 __cxa_get_globals + 0
7   libc++abi.dylib                     0x00007fff6ad33dfe _ZSt11__terminatePFvvE + 8
10  redex-all                           0x0000000105b3982d _Z11assert_failPKcS0_jS0_S0_z + 253
19  libsystem_pthread.dylib             0x00007fff6d7ed26f _pthread_start + 70
9   libc++abi.dylib                     0x00007fff6ad26bb9 __cxa_get_globals + 0
20  libsystem_pthread.dylib             0x00007fff6d7e9415 thread_start + 13
10  redex-all                           0x0000000105b3982d _Z11assert_failPKcS0_jS0_S0_z + 253
16  redex-all                           0x000000010571dcc4 _ZZN9WorkQueueIP8DexClassDnDnE7run_allERKDnENKUlP11WorkerStateIS1_DnDnEmE_clES7_m + 148
Traceback (most recent call last):
  File ".bootstrap/_pex/pex.py", line 328, in execute
  File ".bootstrap/_pex/pex.py", line 261, in _wrap_coverage
  File ".bootstrap/_pex/pex.py", line 293, in _wrap_profiling
  File ".bootstrap/_pex/pex.py", line 371, in _execute
  File ".bootstrap/_pex/pex.py", line 429, in execute_entry
  File ".bootstrap/_pex/pex.py", line 434, in execute_module
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 180, in run_module
    fname, loader, pkg_name)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "native/redex/redex.py", line 893, in <module>
  File "native/redex/redex.py", line 870, in run_redex
  File "native/redex/redex.py", line 220, in run_redex_binary
RuntimeError: redex-all crashed with exit code -6!
```
This change proposes avoiding creating a deobfuscated name alias when a type already exists.

Reviewed By: justinjhendrick

Differential Revision: D13775701

fbshipit-source-id: f7bbce2df875a1b3bd6451a7d4f57d6717afcb5b