Fix this-capturing lambda-related C++20 compile errors
Summary:
Address C++20 errors related to capturing of `this`, as discovered by redex-oss-build:

```
../opt/class-merging/ClassMergingPass.cpp: In lambda function:
../opt/class-merging/ClassMergingPass.cpp:147:23: error: implicit capture of ‘this’ via ‘[=]’ is deprecated in C++20 [-Werror=deprecated]
  147 |   after_configuration([=] {
      |                       ^
../opt/class-merging/ClassMergingPass.cpp:147:23: note: add explicit ‘this’ or ‘*this’ capture
```

The more concise `[=,this]` isn't yet supported by C++17, therefore this diff always explicitly list the captured variable names.

Reviewed By: ssj933

Differential Revision: D79497169

fbshipit-source-id: 22ccad44487481ee9821edfe28146ade48f6ef3b