Add missing `#include <functional>` to `MergingStrategies.h`
Summary:
Caused the OSS build to fail:

```
In file included from ../repo/service/class-merging/MergingStrategies.cpp:8:
../repo/service/class-merging/MergingStrategies.h:14:28: error: 'function' in namespace 'std' does not name a template type
   14 | using GroupWalkerFn = std::function<void(const ConstTypeVector&)>;
      |                            ^~~~~~~~
```

___

overriding_review_checks_triggers_an_audit_and_retroactive_review
Oncall Short Name: redex

Differential Revision: D101145359

fbshipit-source-id: 02e058115a188e066a14c2becb419519f007dee1