Add missing `#include <functional>` to `AnnotationSignatureParser.h`
Summary:
Caused the Debian 13 OSS build to fail:

```
In file included from ../repo/libredex/AnnotationSignatureParser.cpp:8:
../repo/libredex/AnnotationSignatureParser.h:17:16: error: 'function' in namespace 'std' does not name a template type
   17 |     const std::function<bool(const DexEncodedValueString*, DexClass*)>& pred);
      |                ^~~~~~~~
../repo/libredex/AnnotationSignatureParser.h:12:1: note: 'std::function' is defined in header '<functional>'; this is probably fixable by adding '#include <functional>'
```

___

overriding_review_checks_triggers_an_audit_and_retroactive_review
Oncall Short Name: redex

Differential Revision: D101101642

fbshipit-source-id: 9a96a95b1af00dae352ab8b4b0602497b14c34bd