Add missing `#include <functional>` to `InterDexGrouping.h`
Summary:
Caused the OSS build to fail:

```
In file included from ../repo/service/class-merging/InterDexGrouping.cpp:8:
../repo/service/class-merging/InterDexGrouping.h:62:32: error: no template named 'function' in namespace 'std'
   62 |                     const std::function<void(const InterdexSubgroupIdx,
      |                           ~~~~~^
```

___

overriding_review_checks_triggers_an_audit_and_retroactive_review
Oncall Short Name: redex

Differential Revision: D101121099

fbshipit-source-id: c7e888b7fb817204cd1b823ff31c87785d59084f