Use containers Debian 11/12, Ubuntu 22.04/24.04 for github actions (#943)
Summary:
This makes all supported distros being tested.

- Increased java target version to 8, which because 1.7 is no longer supported by the JDK version (21) in Ubuntu 24.04:

```
javac -source 1.7 -target 1.7 -cp build -d build -sourcepath java java/com/facebook/R.java
warning: [options] bootstrap class path not set in conjunction with -source 7
error: Source option 7 is no longer supported. Use 8 or later.
error: Target option 7 is no longer supported. Use 8 or later.
```

- Build GoogleTest with `-std=gnu++17` to enable string_view matchers, which is now being used by some tests.


Differential Revision: D77059596