fix instr test sdk version
Summary:
Fix this error when running redex instrumentation tests

```
com.android.ddmlib.InstallException: -26: Package com.facebook.redex.test.instr new target SDK 0 doesn't support runtime permissions but the old target SDK 23 does.
```

Reviewed By: thezhangwei

Differential Revision: D9189551

fbshipit-source-id: f9ceef6209844a1db527de6fd2e415ca674bd89c