fix lldb "-o" option usage
Summary:
I tried to run lldb command scripted generated by Redex.py. However,  it has the following error:
>target create "set"
error: unable to find executable for 'set'

Current command is:
lldb -o settings set target.source-map "." ***

The reason is the string should be quoted after "-o" option.

This diff adds ''

Reviewed By: agampe

Differential Revision: D33858039

fbshipit-source-id: b1aa734871bfc607220f51b477f67dcb9dc9ec71