Add option to allow missing IDs
Summary:
Sometimes hprof dumps seem to be broken and miss definitions of objects. Add a switch that may allow some cases (currently object array, only).

Example:
`$ python3 dump_classes_from_hprof.py --hprof test.hprof`
```
Traceback (most recent call last):
  File "dump_classes_from_hprof.py", line 1459, in <module>
    hp = parse_filename(args.hprof)
  File "dump_classes_from_hprof.py", line 68, in parse_filename
    return parse_hprof_dump(open(filename, "rb"))
  File "dump_classes_from_hprof.py", line 58, in parse_hprof_dump
    hprof_data.resolve()
  File "dump_classes_from_hprof.py", line 992, in resolve
    obj.resolve(self)
  File "dump_classes_from_hprof.py", line 733, in resolve
    obj, "No object for %x (index %d in %x)", obj, i, self.object_id
  File "dump_classes_from_hprof.py", line 1010, in resolve_object_id
    raise RuntimeError(fmt % args)
RuntimeError: No object for 1541c2f8 (index 10272 in 14204914)
```
`$ python3 dump_classes_from_hprof.py --hprof test.hprof --allow_missing_ids`
```
WARNING:root:No entity for 1541c2f8 (index 10272 in 14204914)
[classes dumped]
```

Reviewed By: amnn

Differential Revision: D23137455

fbshipit-source-id: c4624d2f069acf9ac10549d6ab6917a4fd111718