Fix compiler error regarding 'struct stat' for promotion
Summary:
I don't know why this compiler error is now observed... Is it because of compiler changes?

I was getting this error when I was promoting to redex-staging: `buck build mode/server mode/opt native/redex/... --keep-going`.

```
stderr: native/redex/tools/oatmeal/dump-oat.cpp:3106:15: error: variable has incomplete type 'struct stat'
  struct stat buffer;
              ^
native/redex/tools/oatmeal/dump-oat.cpp:3106:10: note: forward declaration of 'stat'
  struct stat buffer;
         ^
1 error generated.
    When running <c++ preprocess_and_compile>.
    When building rule //native/redex/tools/oatmeal:oatmeal-src-dbg#compile-dump-oat.cpp.oef0585e0,platform007-clang..Rule //native/redex:oatmeal FAILED because Command failed with exit code 1.
stderr: native/redex/tools/oatmeal/dump-oat.cpp:3106:15: error: variable has incomplete type 'struct stat'
  struct stat buffer;
              ^
native/redex/tools/oatmeal/dump-oat.cpp:3106:10: note: forward declaration of 'stat'
  struct stat buffer;
         ^
1 error generated.
```

I added the missing header.

Reviewed By: yuxuanchen1997

Differential Revision: D16260302

fbshipit-source-id: 658cdc4fc540607a7463cb3d49cea29293add05e