Fix implicit copy assignment Clang 11 warnings
Summary:
An implicit copy assignment operator with an explicit copy constructor is a
fatal error (example below) with our compilation flags on Clang 11. Fix the two
instances where this occurs by explicitly defaulting the copy assignment
operator. Also promote one change from D26119136 (https://github.com/facebook/redex/commit/bf2e24daa1e97e5eaa5b1f232926c11c322e983a) that's required to fix the
build to stable.

```
fbandroid/native/redex-stable/libredex/ControlFlow.h:1188:3: error: definition of implicit copy assignment operator for 'InstructionIteratorImpl<false>' is deprecated because it has a user-declared copy constructor [-Werror,-Wdeprecated-copy]
  InstructionIteratorImpl(const InstructionIteratorImpl<false>& rhs)
  ^
fbandroid/native/redex-stable/libredex/ControlFlow.cpp:1380:17: note: in implicit copy assignment operator for 'cfg::InstructionIteratorImpl<false>' first required here
      next_insn =
                ^
In file included from fbandroid/native/redex-stable/libredex/ControlFlow.cpp:8:
In file included from fbandroid/native/redex-stable/libredex/ControlFlow.h:18:
In file included from fbandroid/native/redex-stable/libredex/IRCode.h:19:
fbandroid/native/redex-stable/libredex/IRList.h:525:3: error: definition of implicit copy assignment operator for 'InstructionIteratorImpl<false>' is deprecated because it has a user-declared copy constructor [-Werror,-Wdeprecated-copy]
  InstructionIteratorImpl(const InstructionIteratorImpl<false>& rhs)
  ^
fbandroid/native/redex-stable/libredex/ControlFlow.h:1111:7: note: in implicit copy assignment operator for 'ir_list::InstructionIteratorImpl<false>' first required here
class InstructionIteratorImpl {
      ^
fbandroid/native/redex-stable/libredex/ControlFlow.cpp:1380:17: note: in implicit copy assignment operator for 'cfg::InstructionIteratorImpl<false>' first required here
      next_insn =
                ^
2 errors generated.
```

Reviewed By: yuxuanchen1997

Differential Revision: D27543868 (https://github.com/facebook/redex/commit/90606127c549245f7c4f40932323f5834cb9c79b)

fbshipit-source-id: 6e34ff11d710d6d9efde965f1d0fcf8fa56d8294