Use `-Wno-template-body` instead of `-Wtemplate-body` GCC option
Summary:
Otherwise, older version of GCC complains no such option:

```
error: ‘-Wno-error=template-body’: no option ‘-Wtemplate-body’; did you mean ‘-Wempty-body’?
```

Reviewed By: agampe

Differential Revision: D77408370

fbshipit-source-id: c9c1b0a984d342ef74728956f928f19e5f939ec3