rename inner DexMethod* "m" to "mm" to avoid shadowing warning
Summary:
This is one of a 2 or 3 dirs blocking the move to llvm 15.
As above, to avoid this:
  fbandroid/native/redex/test/unit/MethodSplittingTest.cpp:100:35: error: declaration shadows a structured binding [-Werror,-Wshadow]

Reviewed By: dmm-fb

Differential Revision: D50295299

fbshipit-source-id: d049765517be7b1b2dc521acb5dbb1ff81578fc2