Fix cmake build linux (#347)
Summary:
Fix CMake build for Linux which was failing because of 3 reasons:

1. `find_package` for ZLIB was failing because `find_package` is case-sensitive
2. Multiple references issue because of whole-archive. Fixed by [stackoverflow answer](https://stackoverflow.com/a/14863516/1058787)
3. Undefined reference to `dlsym`

Now

- `cmake.. -DBUIILD_TYPE=Shared && cmake --build .` results is following dependencies linked dynamically:
```bash
root@ubuntu-xenial:/home/vagrant/redex/build-cmake# ldd redex-all
	linux-vdso.so.1 =>  (0x00007ffe2a14a000)
	libboost_system.so.1.58.0 => /usr/lib/x86_64-linux-gnu/libboost_system.so.1.58.0 (0x00007f7af23c8000)
	libboost_regex.so.1.58.0 => /usr/lib/x86_64-linux-gnu/libboost_regex.so.1.58.0 (0x00007f7af20c0000)
	libboost_filesystem.so.1.58.0 => /usr/lib/x86_64-linux-gnu/libboost_filesystem.so.1.58.0 (0x00007f7af1ea8000)
	libboost_program_options.so.1.58.0 => /usr/lib/x86_64-linux-gnu/libboost_program_options.so.1.58.0 (0x00007f7af1c2a000)
	libboost_iostreams.so.1.58.0 => /usr/lib/x86_64-linux-gnu/libboost_iostreams.so.1.58.0 (0x00007f7af1a11000)
	libboost_thread.so.1.58.0 => /usr/lib/x86_64-linux-gnu/libboost_thread.so.1.58.0 (0x00007f7af17eb000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f7af15ce000)
	libjsoncpp.so.1 => /usr/lib/x86_64-linux-gnu/libjsoncpp.so.1 (0x00007f7af139d000)
	libz.so.1 => /lib/x86_64-linux-gnu/libz.so.1 (0x00007f7af1183000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f7af0f7f000)
	libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007f7af0bfd000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f7af08f4000)
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f7af06de000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f7af0314000)
	libicui18n.so.55 => /usr/lib/x86_64-linux-gnu/libicui18n.so.55 (0x00007f7aefeb2000)
	libicuuc.so.55 => /usr/lib/x86_64-linux-gnu/libicuuc.so.55 (0x00007f7aefb1e000)
	libbz2.so.1.0 => /lib/x86_64-linux-gnu/libbz2.so.1.0 (0x00007f7aef90e000)
	librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007f7aef706000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f7af25cc000)
	libicudata.so.55 => /usr/lib/x86_64-linux-gnu/libicudata.so.55 (0x00007f7aedc4f000)
```
- `cmake.. -DBUIILD_TYPE=Static && cmake --build .` results is following dependencies linked dynamically:

```bash
root@ubuntu-xenial:/home/vagrant/redex/build-cmake# ldd redex-all
	linux-vdso.so.1 =>  (0x00007ffe30ed1000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007ff6a7736000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007ff6a7532000)
	libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007ff6a71b0000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007ff6a6ea7000)
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007ff6a6c91000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007ff6a68c7000)
	/lib64/ld-linux-x86-64.so.2 (0x00007ff6a7953000)
```

**Note: Ensured that CMake build for Mac continues to work**
Pull Request resolved: https://github.com/facebook/redex/pull/347

Reviewed By: minjang

Differential Revision: D9976194

Pulled By: justinjhendrick

fbshipit-source-id: c8063da47d27288bd873fb9864b66219c03df880