A quick compiler error fix
Summary:
Some older clang compilers:

   native/redex/libredex/AbstractDomain.h:72:5: error: static_assert failed "Derived is not default constructible"
    static_assert(std::is_default_constructible<Derived>::value,
    ^             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

`AbstractDomainReverseAdaptor` has a default constructor and `DefsDomain` should take this base class's default constructor because of `using AbstractDomainReverseAdaptor::AbstractDomainReverseAdaptor`. But some compilers fail to catch this. Add an explicit `= default` though it's redundant.

Differential Revision: D5005626

fbshipit-source-id: c7161490bb9c060ce03fa3a96774c85e0d404b97