Do not perform class-splitting on primary dex
Summary:
... but only all the other cold-start dexes.

This addresses a bug found recently, where class splitting apparently co-located some methods in a class where some of those methods contained references to secondary dexes, which caused (certain Android versions of) the VM to throw NoClassDefFoundError exception.

Reviewed By: emma0303

Differential Revision: D14508643

fbshipit-source-id: 1bd55eacd5f5d45b843a6fdca29b443e6d2eb343